### ISSUE TITLE
План работ

### ISSUE THREAD

**Issue by GrGolomidov** [caiiiok254/organizer#2]
План работ:

Ознакомление с библиотеками Ознакомиться с библиотекой Curl: https://curl.haxx.se/
Curl используется в командных строках или скриптах для передачи данных.

Делегирование реализуемых функций учитывая пункт 1, Функциональность ТЗ. распределить написание функций для органайзера между участниками.

Реализация функций Реализовать функции для органайзера:
1) Онлайн блокнот
2) Получение актуальных данных о погоде в вашей местности
3) Открытие браузера на выбранной/введенной странице
4) Случайная цитата из bash.
5) Star Wars in ASCII

Слияние проектов участников Создание общего проекта. Структурирование функций органайзера. Объединение функций написанных участниками в единый многофайловый проект.

Отладка и тестирование Проверка приложения на ошибки работы органайзера. Ручное тестирование органайзера

**Comment by webdev-crypto** [comment]
Все работы выполнены, функции написаны, было проведено ручное тестирование, не выявившее критических ошибок!
