### ISSUE TITLE
Онлайн блокнот

### ISSUE THREAD

**Issue by GrGolomidov** [caiiiok254/organizer#3]
Используя набор библиотек curl, а так же онлайн блокнот https://notepad.pw/ необходимо создать функцию, записывающую временную ссылку личного блокнота в локальный файл с пометкой пользователя, после чего откроется браузер на странице, где пользователь сможет вносить свои заметки в режиме онлайн, а затем, обращаясь к файлу, возвращаться к редактированию блокнотов , ориентируясь на ранее оставленные пометки к ссылкам

**Comment by webdev-crypto** [comment]
Выполнено, создана функция notepadpw, соответствующая требованиям!
