### ISSUE TITLE
Открытие браузера на выбранной/введенной странице

### ISSUE THREAD

**Issue by GrGolomidov** [caiiiok254/organizer#5]
Используя функцию system() необходимо открыть новую вкладку браузера и перейти по URL предложенных страниц:
"ЭИОС" https://www.sibsutis.ru/students/eios/
Календарь событий https://sibsutis.ru/about/calendar.php
Либо переход по URL введенной пользователем.

**Comment by webdev-crypto** [comment]
Функция browser создана и соответствует требованиям!
