### ISSUE TITLE
Колонка юмора

### ISSUE THREAD

**Issue by GrGolomidov** [caiiiok254/organizer#6]
1) Используя набор библиотек curl перейти на страницу со случайными цитатами сайта
https://bash.im/random?7013
Получить html-код страницы. Извлечь из кода страницы доступные цитаты и вывести их в стандартный поток вывода.
2) По протоколу telnet (адрес towel.blinkenlights.nl) реализовать просмотр Star Wars.

**Comment by webdev-crypto** [comment]
Функция fun, а также ее производные bashim и starwars созданы, все соответствует требованиям!
